spring:
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: password
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none

